categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"

  - title: ":rocket: Features"
    label: "enhancement"

  - title: ":fire: Removals and Deprecations"
    label: "removal"

  - title: ":bug: Fixes"
    label: "bug"

  - title: ":racehorse: Performance"
    label: "performance"

  - title: ":rotating_light: Testing"
    label: "testing"

  - title: ":construction_worker: Continuous Integration"
    label: "ci"

  - title: ":books: Documentation"
    label: "documentation"

  - title: ":hammer: Refactoring"
    label: "refactoring"

  - title: ":lipstick: Style"
    label: "style"

  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"

category-template: "### $TITLE"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

exclude-contributors:
  - "robbievanleeuwen"

# Custom text at start of release
header: |
  ## ⭐ Highlights

  - Get significant performance improvements for large meshes by using the `pardiso`
    solver, see installation docs [here](https://sectionproperties.readthedocs.io/en/stable/installation.html#installing-pardiso-solver).
    Further performance gains with the introduction of `numba`, both thanks to @TLCFEM.
  - Vastly increased the number of tests, including 19 extra validation tests from
    Pilkey (2002), three of which can be found in the [examples](https://sectionproperties.readthedocs.io/en/stable/examples.html#validation).
  - Added benchmark tests to aid performance improvements.
  - Rhino methods are now support in python 3.10 and 3.11.

template: |
  ## What's Changed

  $CHANGES

footer: |

  **Full changelog:** [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/robbievanleeuwen/section-properties/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
