[tool.poetry]
name = "sectionproperties"
version = "3.0.0"
description = "A python package for the analysis of arbitrary cross-sections using the finite element method."
license = "MIT"
authors = [
    "Robbie van Leeuwen <robbie.vanleeuwen@gmail.com>",
]
maintainers = [
    "Robbie van Leeuwen <robbie.vanleeuwen@gmail.com>",
    "Connor Ferster <connorferster@gmail.com>",
]
readme = "README.md"
homepage = "https://github.com/robbievanleeuwen/section-properties"
repository = "https://github.com/robbievanleeuwen/section-properties"
documentation = "https://sectionproperties.readthedocs.io"
keywords = [
    "cross-section",
    "structural-engineering",
    "finite-element-analysis",
    "computational-mechanics",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
packages = [
    { include = "sectionproperties", from = "src" },
    { include = "src/sectionproperties/py.typed"},
]
include = [
    "*.3dm",
    "*.dxf",
    "*.json",
    "tests/complex_shape.txt",
    "tests/compound_shape.txt",
]

[tool.poetry.urls]
Changelog = "https://github.com/robbievanleeuwen/section-properties/releases"
"Bug Tracker" = "https://github.com/robbievanleeuwen/section-properties/issues"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
numpy = "^1.24.3"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
shapely = "^2.0.1"
triangle = [
    {version = "^20220202", python = "3.8"},
    {version = "^20220202", python = "3.10"},
    {version = "==20200424", python = "3.9"},
]
rich = "^13.4.2"
click = "^8.1.3"
more-itertools = "^9.1.0"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
coverage = {extras = ["toml"], version = "^7.2.7"}
darglint = "^1.8.1"
flake8 = "^6.0.0"
flake8-bugbear = "^23.6.5"
flake8-docstrings = "^1.7.0"
flake8-rst-docstrings = "^0.3.0"
furo = "^2023.5.20 "
isort = "^5.12.0"
pep8-naming = "^0.13.3"
pre-commit = "^3.3.3"
pre-commit-hooks = "^4.4.0"
Pygments = "^2.15.1"
pytest = "^7.3.2"
pytest-check = "^2.1.5"
pyupgrade = "^3.6.0"
sphinx = "^7.0.1"
sphinx-autobuild = "^2021.3.14"
sphinx-click = "^4.4.0"
sphinx-copybutton = "^0.5.2"
sphinxext-opengraph = "^0.8.2"

[tool.poetry.group.cad]
optional = true

[tool.poetry.group.cad.dependencies]
python = ">=3.8.1,<3.10"
cad-to-shapely = "^0.3.1"
rhino-shapley-interop = "^0.0.4"
rhino3dm = "==7.15.0"

[tool.poetry.scripts]
sectionproperties = "sectionproperties.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["sectionproperties", "tests"]

[tool.coverage.report]
show_missing = true

[tool.isort]
profile = "black"
lines_after_imports = 2

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
